version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: monsys_postgres_db
    enviroment:
      - POSTGRES_DB=monsys_postgres_db
      - POSTGRES_USER=monsys-admin
      - POSTGRES_PASSWORD=monsys1
    
    volumes:
      - monsys-data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    healthcheck:
      test: ["CMD-SHELL", "pg_isready - U monsys-admin"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    image: ghcr.io/ewsmyth/monsys:latest
    ports:
      - "7337:7337"
    enviroment:
      - SECRET_KEY=aabbccddeeffgghhiijjkkllmmnnoopp00112233445566778899
      - SECRET_KEY=aabbccddeeffgghhiijjkkll
      - ADMIN_PASSWORD=password
    depends_on:
      - db

volumes:
  postgres-data: